//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_Rename_Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File_Rename_Tool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto update.
        /// </summary>
        public static string auto_update {
            get {
                return ResourceManager.GetString("auto_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Title.
        /// </summary>
        public static string custom_title {
            get {
                return ResourceManager.GetString("custom_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No/Path/Selected.
        /// </summary>
        public static string default_path {
            get {
                return ResourceManager.GetString("default_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As number.
        /// </summary>
        public static string format_setNumber {
            get {
                return ResourceManager.GetString("format_setNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As text.
        /// </summary>
        public static string format_setText {
            get {
                return ResourceManager.GetString("format_setText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can happen due to a number of problems:\n1. There are multiple files with the same name. If executed, these would be overriden.\n2. Invalid characters are used. These are:.
        /// </summary>
        public static string info_message_rename_failed {
            get {
                return ResourceManager.GetString("info_message_rename_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename was not possible.
        /// </summary>
        public static string info_title_rename_failed {
            get {
                return ResourceManager.GetString("info_title_rename_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename successful.
        /// </summary>
        public static string info_title_rename_successful {
            get {
                return ResourceManager.GetString("info_title_rename_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filename:.
        /// </summary>
        public static string new_filename {
            get {
                return ResourceManager.GetString("new_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string open_directory {
            get {
                return ResourceManager.GetString("open_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Format.
        /// </summary>
        public static string text_replace {
            get {
                return ResourceManager.GetString("text_replace", resourceCulture);
            }
        }
    }
}
